{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-xml",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "6.6.2"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.17.1.jar",
          "url": "jackson-dataformat-xml-2.17.1.jar",
          "size": 129184,
          "sha512": "82efd284346872042b9abe77705d3698727d1327510e64da77fc83d6270c434def1110ab966e57051f7c84d8a038c3ed098e09e75661a781f82596810aa51afb",
          "sha256": "bf90159666e64d2b4a43f411552ac0fcdc26fa7c3d2de50533031b05c19b6359",
          "sha1": "e6a168dba62aa63743b9e2b83f4e0f0dfdc143d3",
          "md5": "16f2d81abbfaf4256916f7317f2f24f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "stax2-api",
          "version": {
            "requires": "4.2.2"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.woodstox",
          "module": "woodstox-core",
          "version": {
            "requires": "6.6.2"
          },
          "excludes": [
            {
              "group": "javax.xml.stream",
              "module": "stax-api"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-xml-2.17.1.jar",
          "url": "jackson-dataformat-xml-2.17.1.jar",
          "size": 129184,
          "sha512": "82efd284346872042b9abe77705d3698727d1327510e64da77fc83d6270c434def1110ab966e57051f7c84d8a038c3ed098e09e75661a781f82596810aa51afb",
          "sha256": "bf90159666e64d2b4a43f411552ac0fcdc26fa7c3d2de50533031b05c19b6359",
          "sha1": "e6a168dba62aa63743b9e2b83f4e0f0dfdc143d3",
          "md5": "16f2d81abbfaf4256916f7317f2f24f8"
        }
      ]
    }
  ]
}
