{
  "formatVersion": "1.1",
  "component": {
    "group": "org.junit.platform",
    "module": "junit-platform-launcher",
    "version": "1.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.apiguardian",
          "module": "apiguardian-api",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-launcher-1.10.2.jar",
          "url": "junit-platform-launcher-1.10.2.jar",
          "size": 183814,
          "sha512": "764f1e1a978d8970524a22bf37f807d0a2b94a388abd79d23287ec931266f752e6fedf6599348fd6baf5fcef2105dddb315f680352532e8f2209b56e5d74f7ba",
          "sha256": "aed4f42fb90ada9b347c231f13656fc09121ba20dab6dc646a6bd9d4da31e4aa",
          "sha1": "8125dd29e847ca274dd1a7a9ca54859acc284cb3",
          "md5": "8697c2679111235abe01e66adca88773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-engine",
          "version": {
            "requires": "1.10.2"
          }
        }
      ],
      "files": [
        {
          "name": "junit-platform-launcher-1.10.2.jar",
          "url": "junit-platform-launcher-1.10.2.jar",
          "size": 183814,
          "sha512": "764f1e1a978d8970524a22bf37f807d0a2b94a388abd79d23287ec931266f752e6fedf6599348fd6baf5fcef2105dddb315f680352532e8f2209b56e5d74f7ba",
          "sha256": "aed4f42fb90ada9b347c231f13656fc09121ba20dab6dc646a6bd9d4da31e4aa",
          "sha1": "8125dd29e847ca274dd1a7a9ca54859acc284cb3",
          "md5": "8697c2679111235abe01e66adca88773"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-launcher-1.10.2-javadoc.jar",
          "url": "junit-platform-launcher-1.10.2-javadoc.jar",
          "size": 329938,
          "sha512": "afc28c36e4710ce56dc46bb31115c9a783a339a8ee0c030e25618a4e7d3d698256fd82e1fc7ec5714f59964b6f88a3d4704019aa89786aae3c5fcec48fdc9bda",
          "sha256": "21169f833efd7e56a5eedbbbdfcc33e4b4b9ad452db0cfb3b8ae05a6929f8399",
          "sha1": "92703c665782c6323437617d35a9de394eced673",
          "md5": "286a0edb548725c0977c0728ada0ea99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-platform-launcher-1.10.2-sources.jar",
          "url": "junit-platform-launcher-1.10.2-sources.jar",
          "size": 108036,
          "sha512": "e9eccf15a8fc69e356c00eaa885e62c5e38163bc7092dd71a1b521230294ed1c6c8adbe54de5f6124c6dde81038171ef6605d49b2654a1d0f34881519de27996",
          "sha256": "d3c84fbec86b224e0d2bd49e9335978bdeb6aead9f17cbee4f0e2e8885c7ab89",
          "sha1": "cab5a912975af7dc5d195970f8f1ca27f5caf35a",
          "md5": "e086c298b1cdd13b7a0a93dd4c21d507"
        }
      ]
    }
  ]
}
