{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-databind",
    "version": "2.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.22"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.22.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.22.0.jar",
          "url": "jackson-databind-2.22.0.jar",
          "size": 1703374,
          "sha512": "fb1dfb9a878f1e14ff250374bd94dfe5cbe921ce3390897f3917abdd21ba9dc0df0397139a77ebdf3e86bdf9cd76ac19808aaf56bc782556b271803c9377bd18",
          "sha256": "3520a0351f294699e3e1b7a37c7a726afd81e1a89ae702ac7d47ff347fd2ecbf",
          "sha1": "7aa54fc3755a9285eec2e73053bde1b9b845a9b2",
          "md5": "b3f464be073a99e61bef476e03f001c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.22"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.22.0"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.22.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.22.0.jar",
          "url": "jackson-databind-2.22.0.jar",
          "size": 1703374,
          "sha512": "fb1dfb9a878f1e14ff250374bd94dfe5cbe921ce3390897f3917abdd21ba9dc0df0397139a77ebdf3e86bdf9cd76ac19808aaf56bc782556b271803c9377bd18",
          "sha256": "3520a0351f294699e3e1b7a37c7a726afd81e1a89ae702ac7d47ff347fd2ecbf",
          "sha1": "7aa54fc3755a9285eec2e73053bde1b9b845a9b2",
          "md5": "b3f464be073a99e61bef476e03f001c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-2.22.0-javadoc.jar",
          "url": "jackson-databind-2.22.0-javadoc.jar",
          "size": 6222187,
          "sha512": "18bc008a58a6eaca8304aa606234ba3c4c23c12a4f684a5030499f90a6f858e2887ab8c3e8c95e23905d0f6c828e0e6157a2a500b5e93265655e552bcec86c2b",
          "sha256": "6acf78de854fa5877fde8a27f841790e00dfb6041e0fec97e763b80008e7453c",
          "sha1": "2f23f4b6b27dff0f0058017bc06b9c971208b4cb",
          "md5": "78c2ccd19bdb011748cb931866890fce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-2.22.0-sources.jar",
          "url": "jackson-databind-2.22.0-sources.jar",
          "size": 1256021,
          "sha512": "740397432701f61dac8b4a01fa7b0237d3087ff3c9138b1e4eaa94aef99e8871e378338a0389f0a534b1b2abfd6067d6b45fc52104f64c9fd2050433629ffa2f",
          "sha256": "0d4e71c98fe92d87b0dcc4b8baba865c665671ccf620e664841639aff6b42900",
          "sha1": "5e7c440756f5f74bbe90b423b05110623ec0591e",
          "md5": "c97c3b7552783ee03d760b3261af438a"
        }
      ]
    }
  ]
}
